spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://mongodb:27017/chatdb

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: chat-group