spring:
  config:
    activate:
      on-profile: dev

kafka:
  consumer:
    auto-offset-reset: earliest # 처음 시작할 때 오프셋을 처음부터 읽도록 설정
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.apache.kafka.clients.producer.ProducerConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN